### ISSUE TITLE
Lost UI Shared context

### ISSUE THREAD

**Issue by JohannesRudolph** [sylvaindumont/docker-node-karma-protractor-chrome#12]
When I try to run chromium in this container, I get this error: 

```
sudo docker run --rm -it weboaks/node-karma-protractor-chrome:debian-node8  bash

node@8a0d8e3717e1:/tmp/mypanel$ /usr/bin/chromium --headless --no-sandbox --disable-gpu
[0314/140349.851451:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI shared context.
[0314/140349.852041:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0314/140349.852050:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics
```

**Comment by sylvaindumont** [comment]
Try adding `--remote-debugging-port=9222`, without a remote debugging port, chromium doesn't start in headless mode.
These errors appeared in chromium 64, chromium 63 have none of these, it doesn't seem to block karma or protractor from running.

**Comment by JohannesRudolph** [comment]
Thanks, that clears it up and I could get it working now!

**Comment by mohyeid** [comment]
Once I added --remote-debugging-port=9222, error is gone, but now chrome will not start. Please, help. I get the following: 

Starting b03 08 2018 18:43:53.152:WARN [launcher]: Chrome have not captured in 60000 ms, killing.

I am at version: Google Chrome 64.0.3282.186

**Comment by sylvaindumont** [comment]
@mohyeid  you can learn more about this error in https://github.com/GoogleChrome/puppeteer/issues/1925, but it is not a fatal error and you don't have to worry about it.
`Chrome have not captured in 60000 ms, killing.` could mean chrome doesn't start, or karma can't connect to it. If I remember correctly, setting `--remote-debugging-port` in chrome flags makes karma unable to connect to it.
Try just removing `--remote-debugging-port=9222` from your karma flags and everything should be working fine.
`--remote-debugging-port=9222` is required to keep chrome running  only when launched manually.
