### ISSUE TITLE
Chromium cannot be started from last rebuild

### ISSUE THREAD

**Issue by kuroidoruido** [sylvaindumont/docker-node-karma-protractor-chrome#17]
Hi,

From the last rebuild (2018-07-30T10:39:06.251Z), my pipeline (Karma unit test on Angular 6.0 app) is broken with the error : 

```
30 07 2018 13:10:40.395:ERROR [launcher]: Cannot start Chromium
	Error relocating /usr/lib/chromium/chrome: hb_font_set_variations: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_face_get_table_tags: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_font_set_ptem: symbol not found

30 07 2018 13:10:40.395:ERROR [launcher]: Chromium stdout: 
30 07 2018 13:10:40.395:ERROR [launcher]: Chromium stderr: Error relocating /usr/lib/chromium/chrome: hb_font_set_variations: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_face_get_table_tags: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_font_set_ptem: symbol not found
```

Just to be sure it was not a problem with my new development, I tried to run the pipeline with a branch not modified from some days and with a PASSED status on the last run, and it failed too.

I'm using alpine-node8 image version.

Does someone has the same problem and has fixed it ?

**Comment by kuroidoruido** [comment]
It seem the Harfbuzz version installed is not enought higher to let Chromium 68 to work.

https://hub.docker.com/r/weboaks/node-karma-protractor-chrome/builds/bc3ukrfhobyeasjvgta2cri/ :
```
  ...
(82/116) Installing harfbuzz (1.3.4-r1)
  ...
(96/116) Installing chromium@edge (68.0.3440.75-r0) 
(97/116) Installing chromium-chromedriver@edge (68.0.3440.75-r0)
  ...
```

and if we check on Harfbuzz site, we can see the functions are available with version 1.3.4 :
```
```
https://harfbuzz.github.io/harfbuzz-hb-font.html#hb-font-set-variations => since 1.4.2
https://harfbuzz.github.io/harfbuzz-hb-face.html#hb-face-get-table-tags => since 1.6.0
https://harfbuzz.github.io/harfbuzz-hb-font.html#hb-font-set-ptem => since 1.6.0

I also check Chromium build log, it depend on Harfbuzz but it get it from system, so I think we must install it.
From : http://build.alpinelinux.org/buildlogs/build-edge-x86_64/community/chromium/chromium-68.0.3440.75-r0.log
```
  ...
use_system_harfbuzz=true
  ...
```

I think and `apk add harfbuzz@edge` can solve this issue

**Comment by sylvaindumont** [comment]
@kuroidoruido Thanks a lot for the research. I'm glad to see someone use the alpine version :)
`harfbuzz` is a dependency of gtk and pango and a full upgrade to alpine edge was required to get the correct harfbuzz version. It makes the image 8mo bigger, but everything seems working again.

Let me know if it works on your side.

**Comment by kuroidoruido** [comment]
@sylvaindumont Your docker node+karma+protractor+chromium in alpine version save me a lot of time to build the CI/CD of my project :)

Thanks for the reactivity!
Now all works perfectly like before! Thanks a lot! :)
