### ISSUE TITLE
Protractor hangs on  "I/launcher - 1 instance(s) of WebDriver still running" while using shardTestFiles: true in docker 

### ISSUE THREAD

**Issue by kkrishan** [sylvaindumont/docker-node-karma-protractor-chrome#18]
I am getting this  issue where 1 instance of webdriver remains forever until I abort the test run in jenkins. Protractor hangs at

`I/launcher - 1 instance(s) of WebDriver still running`

**Setup (protractor | headless chrome | docker | jenkins)**
protractor 5.3.2
chromedriverVersion: '2.40.565383'
chrome 'version' => '68.0.3440.75'
platform=Linux 3.10.0-862.3.2.el7.x86_64 x86_64)

**Docker image :**
```
FROM node:9-stretch
RUN apt-get update && 
DEBIAN_FRONTEND="noninteractive" 
apt-get install -y --no-install-recommends 
chromium
dbus-x11
dumb-init
libgconf-2-4 
openjdk-8-jre-headless 
&& rm -rf /var/lib/apt/lists/*
USER node
ENV CHROME_BIN /usr/bin/chromium
ENV DBUS_SESSION_BUS_ADDRESS /dev/null
```

**protractor.conf.js**

```
directConnect: true,
capabilities: {
shardTestFiles: true,
maxInstances: 6,

    'browserName': 'chrome',
    'chromeOptions': {
        args: ['no-sandbox','headless','disable-gpu','window-size=1366,768','enable-logging' ,'v=1','disable-dev-shm-usage'],
    }
},

```
Tried using : ENV DBUS_SESSION_BUS_ADDRESS /dev/null as suggested by few who faced similar issue in docker file but error still exist.

**Comment by sylvaindumont** [comment]
You don't seem to use this image, you should ask your question on StackOverflow. This image works fine on Jenkins, you could try getting closer to [our dockerfile](https://github.com/sylvaindumont/docker-node-karma-protractor-chrome/blob/master/Dockerfile). Also take a look on puppeteer [troubleshooting docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker), they have good advice for running chrome inside docker.
