### ISSUE TITLE
Headless not working since last update

### ISSUE THREAD

**Issue by Orokon** [sylvaindumont/docker-node-karma-protractor-chrome#21]
Since the last update `weboaks/node-karma-protractor-chrome:headless` isn't working anymore. Looks like chrome got some problems.

The error repeats then until failure of pipeline (for me after 6 times).

<details>
<summary>Part of the stacktrace</summary>
17 06 2019 07:24:03.967:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
17 06 2019 07:24:03.975:INFO [launcher]: Launching browsers Chrome_Custom with concurrency unlimited
17 06 2019 07:24:03.980:INFO [launcher]: Starting browser ChromeHeadless
17 06 2019 07:24:09.476:ERROR [launcher]: Cannot start ChromeHeadless
	
DevTools listening on ws://127.0.0.1:9222/devtools/browser/344ff4f9-7316-4e63-818c-2ce61fa42693
[0617/072404.531886:FATAL:proc_util.cc(97)] Check failed: fstatat(proc_self_fd, de->d_name, &s, 0) == 0. 
#0 0x55bb61387209 <unknown>
#1 0x55bb612d24d6 <unknown>
#2 0x55bb612ea8fc <unknown>
#3 0x55bb624c25ba <unknown>
#4 0x55bb624be5f1 <unknown>
#5 0x55bb64b82e36 <unknown>
#6 0x55bb623d5067 <unknown>
#7 0x55bb64b86db4 <unknown>
#8 0x55bb60e2dd77 <unknown>
#9 0x55bb60e3919a <unknown>
#10 0x55bb60e2bb15 <unknown>
#11 0x55bb64f65783 <unknown>
#12 0x55bb64f65885 <unknown>
#13 0x55bb60e359be <unknown>
#14 0x55bb5ea16add ChromeMain
#15 0x7f076f4d92e1 __libc_start_main
#16 0x55bb5ea168fa _start

Received signal 6
#0 0x55bb61387209 <unknown>
#1 0x55bb612d24d6 <unknown>
#2 0x55bb6138761b <unknown>
#3 0x55bb61387c7e <unknown>
#4 0x7f077d0b00e0 <unknown>
#5 0x7f076f4ebfff gsignal
#6 0x7f076f4ed42a abort
#7 0x55bb613871e5 <unknown>
#8 0x55bb612ea870 <unknown>
#9 0x55bb624c25ba <unknown>
#10 0x55bb624be5f1 <unknown>
#11 0x55bb64b82e36 <unknown>
#12 0x55bb623d5067 <unknown>
#13 0x55bb64b86db4 <unknown>
#14 0x55bb60e2dd77 <unknown>
#15 0x55bb60e3919a <unknown>
#16 0x55bb60e2bb15 <unknown>
#17 0x55bb64f65783 <unknown>
#18 0x55bb64f65885 <unknown>
#19 0x55bb60e359be <unknown>
#20 0x55bb5ea16add ChromeMain
#21 0x7f076f4d92e1 __libc_start_main
#22 0x55bb5ea168fa _start
  r8: 0000000000000000  r9: 00007ffc1607abe0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffc1607b640 r13: 00007ffc1607b800 r14: 0000000000000069 r15: 00007ffc1607b650
  di: 0000000000000002  si: 00007ffc1607abe0  bp: 00007ffc1607ae20  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f076f4ebfff  sp: 00007ffc1607ac58
  ip: 00007f076f4ebfff efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
</details>

**Comment by sylvaindumont** [comment]
Does the error still occur if you add `--no-sandbox` flag?

**Comment by sylvaindumont** [comment]
it seems to always happens without `--no-sandbox`, but works fine with `--no-sandbox`, if it happens again even with `--no-sandbox`, please let me know
