### ISSUE TITLE
Upgrade Chromium to latest stable?

### ISSUE THREAD

**Issue by melroy89** [sylvaindumont/docker-node-karma-protractor-chrome#22]
Hi,

Is there any chance you update the Chromium browser to latest stable ([v77.0.3865](https://chromium.woolyss.com/))? 

**EDIT:** I can *NOT* even find version 72 in the `chromedriver` npm package:
https://www.npmjs.com/package/chromedriver?activeTab=versions

😕 

In my project I'm using chromedriver v77. Currently resulting into this error:

```
[23:08:19] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 77
  (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Linux 4.19.0-6-amd64 x86_64)
[23:08:19] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 77
```

Thanks in advance.

Regards,
Melroy 

Ps. I try to use Docker image `weboaks/node-karma-protractor-chrome:debian-node10` in my Gitlab CI.

**Comment by sylvaindumont** [comment]
Hi,
The chromium version in `weboaks/node-karma-protractor-chrome:debian-node10` is `76.0.3809.100`
Unfortunately, it cannot be upgraded because it's the last version available in debian (https://packages.debian.org/buster/chromium). Chromedriver 76 seems to be available.
Chromium 77 is available in alpine, I'm rebuilding the alpine versions with Chromium 77, they will be available in a few hours.
To use the alpine version you need to use the chromedriver binary bundled in the image (https://github.com/sylvaindumont/docker-node-karma-protractor-chrome#alpine-headless)

**Comment by melroy89** [comment]
Ah 76 I can try indeed. I thought it was v72 as stated here: https://github.com/sylvaindumont/docker-node-karma-protractor-chrome/issues/20#issuecomment-471319604

**Comment by melroy89** [comment]
I would like to share my solution/best practice regarding my debian-node10 setup of Docker. Since that involves less changes (in comparison with the alpine version) to the protractor configuration what impact my local testing again.

So in my `package.json` file I defined, this doesn't load v77 now but a fixed [ChromeDriver version 76](https://packages.debian.org/buster/chromium) (see below):

```js
    "pree2e": "webdriver-manager update --versions.chrome=76.0.3809.100",
    "e2e": "ng e2e --webdriver-update false",
```

During Gitlab CI, I run first the `npm run pree2e` and than the normal `npm run e2e`. Like so:

```yml
intergration_test:
  stage: test
  tags:
    - test-headless
  script:
    - npm run pree2e
    - npm run e2e
```

The `test-headless` tag in this config will trigger the Gitlab runner pulling your Docker image (`weboaks/node-karma-protractor-chrome:debian-node10`). 

This works!

![image](https://user-images.githubusercontent.com/628926/67310658-7bf47680-f4fe-11e9-87fa-7a0eb25ccf7f.png)

This may help others I hope...

**Comment by sylvaindumont** [comment]
all images have been updated to `78.0.3904.97`
