### ISSUE TITLE
What does latest point to? Can't find by digest.

### ISSUE THREAD

**Issue by Moulde** [sylvaindumont/docker-node-karma-protractor-chrome#23]
I can't seem to find another tag with the same digest: 469b50c74a75
So what tag does the latest tag point to?

Best regards

**Comment by sylvaindumont** [comment]
`latest` is built from the `xvfb` branch and should theoretically have the same digest than the `xvfb` tag,
they were built on docker hub 15 minutes apart from the same commit.

**Comment by Moulde** [comment]
I'd like to pin the version / tag to use the version that the latest/xvfb tag currently points to.
So I have been looking for the same digest on the tags page.

https://hub.docker.com/r/weboaks/node-karma-protractor-chrome/tags
But I can't seem to find any.

How do i go about finding the tag that the current latest / xvfb tag points to?

**Comment by sylvaindumont** [comment]
They were no commit tag for the xvfb version, only for the headless versions (debian and alpine). I added commit tags for the xvfb version, you should now be able to pin the tag for xvfb.
