### ISSUE TITLE
Changes in alpine-node version

### ISSUE THREAD

**Issue by felipekjr** [sylvaindumont/docker-node-karma-protractor-chrome#24]
Hi, the update that you've made on alpine version (9 days ago) broke my pipeline with karma tests:
```diff
- 22 11 2019 19:00:35.332:ERROR [config]: Error in config file!
- { inspect: [Function: inspect] }
```

Then i setted up to alpine-node10:

&nbsp;&nbsp;&nbsp;&nbsp;`image: weboaks/node-karma-protractor-chrome:alpine-node10`

and everything is back to normal.

Greetings from Brazil ;P

**Comment by sylvaindumont** [comment]
Hi,
[Node 12 is now the latest LTS](https://github.com/nodejs/Release), so I updated the images [from node 10 to node 12](https://github.com/sylvaindumont/docker-node-karma-protractor-chrome/commit/50ca60e41b01e57ac1f4233892f3f99b8c15629a).
Sorry  for the inconvenience.
