### ISSUE TITLE
Root Tag help

### ISSUE THREAD

**Issue by hugoj-goncalves** [sylvaindumont/docker-node-karma-protractor-chrome#25]
Is there a debian-node-8-root anywhere?
I couldn't find it.

There are a lot of tags with root pointing to commits, it's not easy to understand what they are related to.

**Comment by sylvaindumont** [comment]
root images are on the latest node lts, node-8 node-10 and node-12 tags are rootless, the only image with root and node 8 is the debian-root image built when node 8 was the latest lts, the tag `debian-root-53ca153bb24e7b7504e77839384e284aa96d73cc`, but it was built 2 years ago. To get a node 8 image with a recent chromium you could try rebuilding [the dockerfile from this commit](https://github.com/sylvaindumont/docker-node-karma-protractor-chrome/blob/53ca153bb24e7b7504e77839384e284aa96d73cc/Dockerfile) now, or build [the node 8 rootless dockerfile](https://github.com/sylvaindumont/docker-node-karma-protractor-chrome/blob/debian-node8/Dockerfile) with the `USER node` line removed

**Comment by hugoj-goncalves** [comment]
well the `debian-root-53ca153bb24e7b7504e77839384e284aa96d73cc` was enough for my needs
I'll probably update my project to node 12 soon anyways.

Thank you very much.
