### ISSUE TITLE
image node tags & root access 

### ISSUE THREAD

**Issue by sysmat** [sylvaindumont/docker-node-karma-protractor-chrome#29]
Is it possible to have tags that control node version and root access, something like **debian-nodeX-root**?
- do you support node 15, in README it will be fine to update which node version is supported by the image tag?
- debian-root have node 12 & npm 6 which is fixed and too low based on node LTS 

Regards, Tomaž

**Comment by sylvaindumont** [comment]
Sorry for the delay, and thanks for reminding me about the outdated versions in the readme.
* most tags are now based on node 14 
* `debian` and `alpine` tags now have a node 16 tag
* root tags now have a node specific tags like `debian-root-node14`
