### ISSUE TITLE
Running as root without --no-sandbox is no longer supported

### ISSUE THREAD

**Issue by michaelarnauts** [sylvaindumont/docker-node-karma-protractor-chrome#7]
This image runs chrome as user root, and that's not supported anymore in the latest chrom(e|ium)

**Comment by sylvaindumont** [comment]
chrom(e|ium) has never worked in a docker container without --no-sandbox, if you know a way to run it without --no-sandbox by using a certain user, I'm glad to add it to this image, it will simplify the protactor/karma configs

**Comment by sylvaindumont** [comment]
As recommended in by ebidel in https://github.com/GoogleChrome/puppeteer/issues/379#issuecomment-358500565, chrome is no longer run as root in alpine and headless images.
But it doesn't fix `Network namespace supported, but failed`, chrome still need `--no-sandbox` or docker  `--cap-add=SYS_ADMIN`.

**Comment by sylvaindumont** [comment]
Even with another user, `--no-sandbox` is still required, and on debian, running chromium with an unprivileged user causes `libudev: udev_has_devtmpfs: name_to_handle_at on /dev:
Operation not permitted`
