### ISSUE TITLE
Please created versioned Dockerfiles

### ISSUE THREAD

**Issue by grouchal** [sylvaindumont/docker-node-karma-protractor-chrome#9]
The change to Node 8 in the last days has broken our pipelines.

We need to build against node 7 to verify that all will be built correctly.

It would be much better if we could specify:

`weboaks/node-karma-protractor-chrome:node7` or

`weboaks/node-karma-protractor-chrome:1.0.1`

so that we can explicitly always use the same version.

a latest version:

`weboaks/node-karma-protractor-chrome:latest` could then be the version that has always the latest changes.

**Comment by grouchal** [comment]
To all - you have updated this image and broken our builds again - it would be really great if you could add versions to the docker builds so that we can always grab a stable version and not always automatically get the changes as soon as you make them.

**Comment by sylvaindumont** [comment]
@grouchal @carusology the last commit has changed the default user from `root` to `chromium`, hoping to fix #7, but it didn't help. The alpine image still work fine without the root user, can you tell me what broke, I will revert if needed.

Concerning the versionned images, I use automated builds so I will keep a branch for each version, as done in https://github.com/fholzer/docker-nginx-brotli, the question is, which branch do I keep updated with the latest changes?

I think I will create `alpine:6,7,8,9,` and `headless:6,7,8,9` variants. I will add keep 8 and 9 versions updated with the latest changes (the last user change for example), and let the previous version unmodified to avoid breaking builds.

**Comment by sylvaindumont** [comment]
it was causing `libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted`
It seems fixable by adding more permissions to the container but the whole point of the commit was to give it fewer permissions, so I reverted the commit.

**Comment by sylvaindumont** [comment]
@grouchal `libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted` still happen with the root user, but doesn't seems critical. I've restored the root user on the debian headless image so your builds should work again, but can you tell me what was your errors, so I can restore an unprivileged user without broking more builds.

**Comment by grouchal** [comment]
@sylvaindumont what we need is not to have the versions of the OS added to the tagging, but the version of this image.

This would mean that if we used `weboaks/node-karma-protractor-chrome:latest` we would get the problems that we have got today. However we would be able to get back to the stable version from December by using something like:

`weboaks/node-karma-protractor-chrome:1.0.1`

Of course you can also pack in the rest of pieces needed for targeting so that the full name would be:

`weboaks/node-karma-protractor-chrome-headless-6:1.0.1`
`weboaks/node-karma-protractor-chrome-headless-7:1.0.1`
`weboaks/node-karma-protractor-chrome-headless-8:1.0.1`
`weboaks/node-karma-protractor-chrome-alpine-6:1.0.1`
`weboaks/node-karma-protractor-chrome-alpine-7:1.0.1`
`weboaks/node-karma-protractor-chrome-alpine-8:1.0.1`

For those who want to use latest they would use:
`weboaks/node-karma-protractor-chrome-headless-6:latest`
`weboaks/node-karma-protractor-chrome-headless-7:latest`
`weboaks/node-karma-protractor-chrome-headless-8:latest`
`weboaks/node-karma-protractor-chrome-alpine-6:latest`
`weboaks/node-karma-protractor-chrome-alpine-7:latest`
`weboaks/node-karma-protractor-chrome-alpine-8:latest`

**Comment by sylvaindumont** [comment]
@grouchal  The tagged node versions don't fix problems like the last ones but allow us to use automated builds to have an always up to date node and chromium.

The best way to fix the problem and allow rollback is to set up a travis build for pushing images tagged with commit hash. This way we could have always up to date images with automated build and tags specifics to commit to pin node and chromium versions and rollback if needed.

**Comment by grouchal** [comment]
@sylvaindumont perfect solution! ;-)

**Comment by grouchal** [comment]
OK you have added the chromium users again - we can't use this unstable image any longer it is just breaking our builds and creating lots of extra stress and work.

Thanks for creating this initially - good luck for the future.

**Comment by sylvaindumont** [comment]
@grouchal sorry, you didn't told me what was broken, so I assumed it was just a migration problem. 
`debian-a530da03a135b91709772b42e0e9466a4c9c034f` tag has the root user and will not change.
I will revert the change again, but it would be better to fix the unprivileged image.

**Comment by grouchal** [comment]
@sylvaindumont don't worry we have our own image now.
